create table if not exists categorias_accesorios (
    id_categoria bigint generated by default as identity primary key,
    nombre text not null unique
);

create table if not exists productos_accesorios (
    id_producto bigint generated by default as identity primary key,
    id_categoria bigint references categorias_accesorios(id_categoria) on delete set null,
    nombre text not null,
    descripcion text,
    imagen_url text,
    creado_en timestamptz not null default now()
);

create table if not exists variantes_accesorios (
    id_variante bigint generated by default as identity primary key,
    id_producto bigint not null references productos_accesorios(id_producto) on delete cascade,
    precio numeric(12, 0) not null default 0,
    stock integer not null default 0
);

alter table categorias_accesorios enable row level security;
alter table productos_accesorios enable row level security;
alter table variantes_accesorios enable row level security;

drop policy if exists "lectura publica categorias" on categorias_accesorios;
drop policy if exists "lectura publica productos" on productos_accesorios;
drop policy if exists "lectura publica variantes" on variantes_accesorios;

create policy "lectura publica categorias"
on categorias_accesorios for select
using (true);

create policy "lectura publica productos"
on productos_accesorios for select
using (true);

create policy "lectura publica variantes"
on variantes_accesorios for select
using (true);

insert into categorias_accesorios (nombre)
values ('Conductor'), ('Moto')
on conflict (nombre) do nothing;
