create table if not exists marcas (
    id_marca bigint generated by default as identity primary key,
    nombre text not null unique
);

create table if not exists categorias_motos (
    id_categoria bigint generated by default as identity primary key,
    nombre text not null unique,
    descripcion text
);

create table if not exists modelos (
    id_modelo bigint generated by default as identity primary key,
    nombre text not null,
    id_marca bigint references marcas(id_marca) on delete set null,
    id_categoria bigint references categorias_motos(id_categoria) on delete set null,
    imagen_url text
);

create table if not exists categorias_accesorios (
    id_categoria_accesorio bigint generated by default as identity primary key,
    nombre text not null unique,
    imagen_url text
);

create table if not exists productos_accesorios (
    id_producto bigint generated by default as identity primary key,
    nombre text not null,
    descripcion text,
    id_categoria_accesorio bigint references categorias_accesorios(id_categoria_accesorio) on delete set null,
    imagen_url text,
    activo boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists variantes_accesorios (
    id_variante bigint generated by default as identity primary key,
    id_producto bigint not null references productos_accesorios(id_producto) on delete cascade,
    precio numeric(12, 2) not null default 0,
    stock integer not null default 0,
    activo boolean not null default true,
    created_at timestamptz not null default now()
);

alter table marcas enable row level security;
alter table categorias_motos enable row level security;
alter table modelos enable row level security;
alter table categorias_accesorios enable row level security;
alter table productos_accesorios enable row level security;
alter table variantes_accesorios enable row level security;

drop policy if exists "lectura publica marcas" on marcas;
drop policy if exists "lectura publica categorias motos" on categorias_motos;
drop policy if exists "lectura publica modelos" on modelos;
drop policy if exists "lectura publica categorias accesorios" on categorias_accesorios;
drop policy if exists "lectura publica productos accesorios" on productos_accesorios;
drop policy if exists "lectura publica variantes accesorios" on variantes_accesorios;

create policy "lectura publica marcas"
on marcas for select
using (true);

create policy "lectura publica categorias motos"
on categorias_motos for select
using (true);

create policy "lectura publica modelos"
on modelos for select
using (true);

create policy "lectura publica categorias accesorios"
on categorias_accesorios for select
using (true);

create policy "lectura publica productos accesorios"
on productos_accesorios for select
using (true);

create policy "lectura publica variantes accesorios"
on variantes_accesorios for select
using (true);

insert into categorias_motos (nombre, descripcion)
values
    ('Naked', 'Ciudad'),
    ('Deportivas', 'Velocidad'),
    ('Touring', 'Viajes')
on conflict (nombre) do nothing;

insert into categorias_accesorios (nombre)
values
    ('Casco'),
    ('Guante'),
    ('Chaqueta No Reflectiva'),
    ('Botas'),
    ('Impermeable'),
    ('Maletero'),
    ('Intercomunicador')
on conflict (nombre) do nothing;
