create table if not exists marcas (
    id_marca bigint generated by default as identity primary key,
    nombre text not null unique
);

create table if not exists categorias_motos (
    id_categoria bigint generated by default as identity primary key,
    nombre text not null unique,
    descripcion text
);

create table if not exists modelos (
    id_modelo bigint generated by default as identity primary key,
    nombre text not null,
    id_marca bigint references marcas(id_marca) on delete set null,
    id_categoria bigint references categorias_motos(id_categoria) on delete set null,
    imagen_url text,
    descripcion text,
    precio numeric(12, 2) not null default 0,
    stock integer not null default 0,
    cilindrada integer,
    motor text,
    potencia text
);

create table if not exists categorias_accesorios (
    id_categoria_accesorio bigint generated by default as identity primary key,
    nombre text not null unique,
    imagen_url text
);

create table if not exists productos_accesorios (
    id_producto bigint generated by default as identity primary key,
    nombre text not null,
    descripcion text,
    id_categoria_accesorio bigint references categorias_accesorios(id_categoria_accesorio) on delete set null,
    imagen_url text,
    activo boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists variantes_accesorios (
    id_variante bigint generated by default as identity primary key,
    id_producto bigint not null references productos_accesorios(id_producto) on delete cascade,
    precio numeric(12, 2) not null default 0,
    stock integer not null default 0,
    activo boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists pedidos (
    id_pedido bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete set null,
    email text,
    total numeric(12, 2) not null default 0,
    estado text not null default 'simulado',
    created_at timestamptz not null default now()
);

create table if not exists detalle_pedidos (
    id_detalle bigint generated by default as identity primary key,
    id_pedido bigint not null references pedidos(id_pedido) on delete cascade,
    producto_id text not null,
    tipo text not null,
    nombre text not null,
    precio numeric(12, 2) not null default 0,
    cantidad integer not null default 1,
    subtotal numeric(12, 2) not null default 0
);

alter table marcas enable row level security;
alter table categorias_motos enable row level security;
alter table modelos enable row level security;
alter table categorias_accesorios enable row level security;
alter table productos_accesorios enable row level security;
alter table variantes_accesorios enable row level security;
alter table pedidos enable row level security;
alter table detalle_pedidos enable row level security;

drop policy if exists "lectura publica marcas" on marcas;
drop policy if exists "lectura publica categorias motos" on categorias_motos;
drop policy if exists "lectura publica modelos" on modelos;
drop policy if exists "lectura publica categorias accesorios" on categorias_accesorios;
drop policy if exists "lectura publica productos accesorios" on productos_accesorios;
drop policy if exists "lectura publica variantes accesorios" on variantes_accesorios;
drop policy if exists "usuarios leen sus pedidos" on pedidos;
drop policy if exists "usuarios crean sus pedidos" on pedidos;
drop policy if exists "usuarios leen detalle de sus pedidos" on detalle_pedidos;
drop policy if exists "usuarios crean detalle de sus pedidos" on detalle_pedidos;
drop policy if exists "usuarios autenticados insertan modelos" on modelos;
drop policy if exists "usuarios autenticados actualizan modelos" on modelos;
drop policy if exists "usuarios autenticados eliminan modelos" on modelos;
drop policy if exists "usuarios autenticados insertan accesorios" on productos_accesorios;
drop policy if exists "usuarios autenticados actualizan accesorios" on productos_accesorios;
drop policy if exists "usuarios autenticados eliminan accesorios" on productos_accesorios;

create policy "lectura publica marcas"
on marcas for select
using (true);

create policy "lectura publica categorias motos"
on categorias_motos for select
using (true);

create policy "lectura publica modelos"
on modelos for select
using (true);

create policy "lectura publica categorias accesorios"
on categorias_accesorios for select
using (true);

create policy "lectura publica productos accesorios"
on productos_accesorios for select
using (true);

create policy "lectura publica variantes accesorios"
on variantes_accesorios for select
using (true);

create policy "usuarios leen sus pedidos"
on pedidos for select
using (auth.uid() = user_id);

create policy "usuarios crean sus pedidos"
on pedidos for insert
with check (auth.uid() = user_id);

create policy "usuarios leen detalle de sus pedidos"
on detalle_pedidos for select
using (exists (select 1 from pedidos where pedidos.id_pedido = detalle_pedidos.id_pedido and pedidos.user_id = auth.uid()));

create policy "usuarios crean detalle de sus pedidos"
on detalle_pedidos for insert
with check (exists (select 1 from pedidos where pedidos.id_pedido = detalle_pedidos.id_pedido and pedidos.user_id = auth.uid()));

create policy "usuarios autenticados insertan modelos"
on modelos for insert to authenticated
with check (true);

create policy "usuarios autenticados actualizan modelos"
on modelos for update to authenticated
using (true)
with check (true);

create policy "usuarios autenticados eliminan modelos"
on modelos for delete to authenticated
using (true);

create policy "usuarios autenticados insertan accesorios"
on productos_accesorios for insert to authenticated
with check (true);

create policy "usuarios autenticados actualizan accesorios"
on productos_accesorios for update to authenticated
using (true)
with check (true);

create policy "usuarios autenticados eliminan accesorios"
on productos_accesorios for delete to authenticated
using (true);

insert into categorias_motos (nombre, descripcion)
values
    ('Naked', 'Ciudad'),
    ('Deportivas', 'Velocidad'),
    ('Touring', 'Viajes')
on conflict (nombre) do nothing;

insert into categorias_accesorios (nombre)
values
    ('Casco'),
    ('Guante'),
    ('Chaqueta No Reflectiva'),
    ('Botas'),
    ('Impermeable'),
    ('Maletero'),
    ('Intercomunicador')
on conflict (nombre) do nothing;
